version: '3.7'

services:
  nginx:
    image: nginx
    ports:
      - '8080:80'
    links:
      - php-fpm
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
    networks:
      - code-network
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./
    volumes:
      - .:/app
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/docker-php-ext-xdebug.ini
    networks:
      - code-network
    depends_on:
      - db
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=SmartHouse"

  db:
    image: webhippie/mariadb
    ports:
      - 3306:3306
    networks:
      - code-network
    environment:
      MARIADB_ROOT_PASSWORD: lrv7
      MARIADB_PASSWORD: lrv7
      MARIADB_DATABASE: lrv7
      MARIADB_USERNAME: lrv7

networks:
  code-network:
    driver: bridge
    ipam:
      driver: default
