version: '3.7'

services:
  nginx:
    image: nginx
    ports:
      - '8080:80'
    links:
      - php-fpm
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
    networks:
      - code-network
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./
    volumes:
      - .:/app
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/docker-php-ext-xdebug.ini
    networks:
      - code-network
    depends_on:
      - db
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=SmartHouse"

  db:
    image: mysql:8
    ports:
      - 3307:3306
    networks:
      - code-network
    environment:
      MYSQL_ROOT_PASSWORD: 261200
      MYSQL_PASSWORD: smf5
      MYSQL_DATABASE: smf5
      MYSQL_USER: smf5

networks:
  code-network:
    driver: bridge
    ipam:
      driver: default
